### ISSUE TITLE
Make sure that the keys are immutable

### ISSUE THREAD

**Issue by formrre** [formrre/soft-heap-haskell#5]
We don't want the keys to be mutable as this could violate the necessary invariant of the Soft heaps. Can we prevent the type:
`SHItem s element key`
from being instantiated to
`SHItem s element (MutKey s key)` where
`data MutKey s a=MutKey (STRef s a)` 
or any other situation, where the keys could change over time i.e. STArray, while passing the state thread parameters checked by runST (i.e. disregarding unsafePerformIO or the low-level MutVar#).

see: https://mail.haskell.org/pipermail/haskell-cafe/2017-August/127760.html

**Comment by wyager** [comment]
So maybe I'm missing something here, but isn't there an `Ord` constraint on the keys? It's impossible to write a (sane) `Ord` instance on mutable keys. If `STRef` had an `Ord` instance (it doesn't, but hypothetically) it would have to be over the pointer destination, not the dereferenced value. So I think `Ord` conveniently forces the correct (immutable) semantics here (because `compare` is pure).

**Comment by formrre** [comment]
Yes, it is so, I was missing this, thank you very much for pointing this out.

I cannot write an instance of Ord for mutable keys as compare would have the type:

compare ::  MutKey s a -> MutKey s a -> ST s (Ordering) 
instead of the required 
compare :: MutKey s a -> MutKey s a -> Ordering
